[pyprland]
plugins = [
  "scratchpads",
  # "lost_windows",
  # "monitors",
  # "shift_monitors",
  # "toggle_dpms",
  # "magnify",
  # "expose",
  # "workspaces_follow_focus",
]

[workspaces_follow_focus]
max_workspaces = 9
#
# [expose]
# include_special = false

[scratchpads.dropterm]
animation = "fromTop"
command = "kitty --class term-drop --config /home/kuba/.config/kitty/qterm.conf tmux new -A -s dropterm"
class = "term-drop"
lazy = true
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"

# [scratchpads.dropterm2]
# animation = "fromBottom"
# command = "wezterm --class wezterm-drop"
# class = "wezterm-drop"
# lazy = true
# size = "90% 90%"
# max_size = "1920px 90%"
# excludes = "*"

[scratchpads.top]
animation = "fromBottom"
command = "kitty --class kitty_btm --config ~/.config/kitty/qterm.conf btm"
lazy = true
class = "kitty_btm"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"

[scratchpads.slack]
animation = "fromBottom"
command = "/usr/bin/slack --disable-gpu-compositing --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer --enable-features=WaylandWindowDecorations --silent"
class = "Slack"
match_by = "initialTitle"
initialTitle = "Slack"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"

[scratchpads.whatsapp]
animation = "fromBottom"
# command = "whatsapp-for-linux"
# class = "whatsapp-for-linux"
command = "whatsie"
class = "com.ktechpit.whatsie"
lazy = true
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"

[scratchpads.discord]
animation = "fromBottom"
command = "/usr/bin/discord"
class = "discord"
lazy = true
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"

[scratchpads.obsidian]
animation = "fromBottom"
command = "obsidian obsidian://open?vault=notes"
class = "obsidian"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"

[scratchpads.ytmusic]
animation = "fromBottom"
command = "/usr/bin/youtube-music"
class = "YouTube Music"
lazy = true
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
# unfocus = "hide"

# [scratchpads.gmeet]
# command = "/opt/google/chrome-beta/google-chrome-beta \"--profile-directory=Profile 1\" --app-id=kjgfgldnnfoeklkmfkjfagphfepbbdan"
# animation = "fromRight"
# class = "chrome-kjgfgldnnfoeklkmfkjfagphfepbbdan-Profile_1"
# size = "50% 90%"
# max_size = "1920px 90%"
# lazy = true
# shared_pid = true
# unfocus = "hide"

[scratchpads.chatbox]
animation = "fromRight"
command = "chatbox"
class = "xyz.chatboxapp.app"
size = "33% 90%"
max_size = "1280px 90%"
lazy = true
excludes = ["volume"]

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "pavucontrol"
lazy = true
size = "33% 66%"
excludes = ["chatbox"]
max_size = "1280px 66%"

# todo
# [scratchpads.firefox]
# animation = "fromBottom"
# command = ":"
# class = "top"
# class_match
# sizje = "70% 90%"


# [monitors]
# unknown = "wlrlui"
#
# [monitors.placement]
# "Acer".leftOf = "HDMI-0"
# "Sony".topOf = "eDP-1"
