# Theme (solarized)
# set $bg-color	           #268bd2
# set $inactive-bg-color   #073642
# set $text-color          #fdf6e3
# set $inactive-text-color #fdf6e3
# set $urgent-bg-color     #dc322f
# set $indicator-color     #073642
# set $transparent-color   #ffffff00
# set $child-border-color  #268bd2
# window colors (solarized)
#                       border              background         text                 indicator         child-border
# client.focused          $bg-color           $bg-color          $text-color          $indicator-color  $bg-color
# client.unfocused        $inactive-bg-color  $inactive-bg-color $inactive-text-color $indicator-color  $transparent-color
# client.focused_inactive $inactive-bg-color  $inactive-bg-color $inactive-text-color $indicator-color  $transparent-color
# client.urgent           $urgent-bg-color    $urgent-bg-color   $text-color          $indicator-color  $transparent-color

# Theme (gruvbox)
set $bg #282828
set $red #cc241d
set $green #98971a
set $yellow #d79921
set $blue #458588
set $purple #b16286
set $aqua #689d68
set $gray #a89984
set $darkgray #1d2021

# green gruvbox
# class                 border|backgr|text|indicator|child_border
#client.focused          $green $green $darkgray $purple $darkgray
#client.focused_inactive $darkgray $darkgray $yellow $purple $darkgray
#client.unfocused        $darkgray $darkgray $yellow $purple $darkgray
#client.urgent           $red $red $gray $red $red

# blue gruvbox
# class                 border|backgr|text|indicator|child_border
client.focused          $blue $blue $darkgray $purple $darkgray
client.focused_inactive $darkgray $darkgray $yellow $purple $darkgray
client.unfocused        $darkgray $darkgray $yellow $purple $darkgray
client.urgent           $red $red $gray $red $red

### Gaps and borders ###
# You can also use any non-zero value if you'd like to have a border
default_floating_border normal
default_border pixel 2
gaps inner 8
gaps outer 128
# Only enable gaps on a workspace when there is at least one container
# smart_gaps on
# outer gaps will only be enabled if a workspace has exactly one child
smart_gaps inverse_outer

# Only enable borders on a workspace with more than one child
smart_borders on

### Status Bar:
#
# Read `man 5 sway-bar` for more information about this section.
# Waybar has it's own configuration files
bar {
    position top
    swaybar_command waybar
}
