# vim: set filetype=conf :
set $mod Mod1
# POWER MANAGEMENT
set $Locker swaylock-blur -- --daemonize --show-failed-attempts --ignore-empty-password
bindsym Control+$mod+l exec $Locker

set $mode_system System (l) lock, (e) logout, (s) suspend, (h) hibernate, (r) reboot, (Shift+s) shutdown
mode "$mode_system" {
    bindsym l exec --no-startup-id $Locker, mode "default"
    bindsym e exec --no-startup-id swaymsg exit, mode "default"
    bindsym s exec --no-startup-id systemctl suspend, mode "default"
    bindsym h exec --no-startup-id systemctl hibernate, mode "default"
    bindsym r exec --no-startup-id systemctl reboot, mode "default"
    bindsym Shift+s exec --no-startup-id systemctl poweroff -i, mode "default"

    # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $sup+q mode "$mode_system"

## Idle configuration
#
for_window [con_mark=idle] inhibit_idle open
bindsym $sup+i [con_mark=idle] inhibit_idle none; mark idle

#exec swayidle -w \
#          timeout 300 '$Locker' \
#         timeout 1200 'swaymsg "output * dpms off"' \
#               resume 'swaymsg "output * dpms on"' \
#         before-sleep '$Locker'
##
# This will lock your screen after 300 seconds of inactivity, then turn off
# your displays after another 300 seconds, and turn your screens back on when
# resumed. It will also lock your screen before your computer goes to sleep.

# disable idle for fullscreen apps
for_window [class=".*"] inhibit_idle fullscreen
for_window [app_id=".*"] inhibit_idle fullscreen
