[General]
4qNVHDn32Zz2cZ5y4pO7ecllqYIlc4SiMWLnPGTlP8I%23=1625042276
GeoLocale=system
Nzgh3Z9VLKKfUh%2BMVIGw1Wlw6DaraSDOx1lI8j7C4hs%23=1626078999
SensitiveInfoMaskOn=true
appendCallerNameForRoomSystem=false
asBarTopMargin=30
autoPlayGif=false
autoScale=true
bForceMaximizeWM=false
blockUntrustedSSLCert=false
captureHDCamera=true
chatListPanelLastWidth=230
conf.crash.enable.auto.uploaddumps=false
conf.webserver=https://us02web.zoom.us
conf.webserver.vendor.default=https://us04web.zoom.us
currentMeetingId=6180974855
deviceID=90:78:41:39:FF:E4
embeddedBrowserForFacebookLogin=false
embeddedBrowserForGoogleLogin=false
embeddedBrowserForSSOLogin=true
enable.host.auto.grab=true
enableAlphaBuffer=true
enableCloudSwitch=false
enableLog=true
enableMiniWindow=true
enableQmlCache=true
enableScreenSaveGuard=false
enableStartMeetingWithRoomSystem=false
enableTestMode=false
enableWaylandShare=false
enablegpucomputeutilization=false
fake.version=
flashChatTime=0
forceEnableTrayIcon=true
forceSSOURL=
host.auto.grab.interval=10
isTransCoding=false
logLevel=info
newMeetingWithVideo=false
playSoundForNewMessage=false
scaleFactor=1
shareBarTopMargin=0
speaker_volume=255
sso_domain=.zoom.us
sso_gov_domain=.zoomgov.com
system.audio.type=default
timeFormat12HoursEnable=true
transcodingUI=true
upcoming_meeting_header_image=
useSystemTheme=false
userEmailAddress=jakub@trint.com

[AS]
lastsharerect=2160, 460, 800, 520
showframewindow=true

[CodeSnippet]
lastCodeType=0
wrapMode=0

[chat.recent]
recentlast.session=

[https%3A]
lh3.googleusercontent.com\a-\AOh14GiKVAq09crUimXuB6yoTG1K02jKzH9CnJO-6kvF=1595928054
us02images.zoom.us\p\h-OsURucSA-Z8aiqfrXbWA\ae45d8b4-2bf4-4a19-a433-684fa9a46843-2687=1591349049

[zoom_new_im]
is_landscape_mode=false
main_frame_pixel_pos_narrow="628,1390"
main_frame_pixel_pos_wide="1693,1390"
