[pyprland]
plugins = ["scratchpads"]

[scratchpads.dropterm]
animation = "fromTop"
# command = "kitty --class term-drop --config /home/kuba/.config/kitty/qterm.conf tmux new -A -s dropterm"
command = "kitty --class term-drop --config /home/kuba/.config/kitty/qterm.conf tmux attach -d -t dropterm"
class = "term-drop"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"

[scratchpads.top]
animation = "fromBottom"
command = "kitty --class kitty_btm --config ~/.config/kitty/qterm.conf btm"
class = "kitty_btm"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"

[scratchpads.slack]
animation = "fromBottom"
command = "/usr/bin/slack --disable-gpu-compositing --ozone-platform=wayland --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer"
# command = "/usr/bin/slack --disable-gpu-compositing --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer --enable-features=WaylandWindowDecorations --silent"
class = "Slack"
# looks like it's needed by pyprland atm
lazy = true
match_by = "initialTitle"
initialTitle = "Slack"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"

[scratchpads.whatsapp]
animation = "fromBottom"
command = "whatsie"
class = "com.ktechpit.whatsie"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"

[scratchpads.discord]
animation = "fromBottom"
command = "/usr/bin/discord"
match_by = "class"
class = "discord"
lazy = true
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"

[scratchpads.obsidian]
animation = "fromBottom"
command = "obsidian obsidian://open?vault=notes"
class = "obsidian"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"

[scratchpads.ytmusic]
animation = "fromBottom"
command = "/usr/bin/youtube-music"
class = "YouTube Music"
lazy = true
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"

# [scratchpads.gmeet]
# command = "/opt/google/chrome/google-chrome --profile-directory=Default --app-id=kjgfgldnnfoeklkmfkjfagphfepbbdan"
# animation = "fromRight"
# class = "chrome-kjgfgldnnfoeklkmfkjfagphfepbbdan-Profile_1"
# size = "50% 90%"
# max_size = "1920px 90%"
# lazy = true
# shared_pid = true
# unfocus = "hide"

[scratchpads.onepass]
animation = "fromBottom"
command = "1password"
class = "1Password"
size = "33% 50%"
max_size = "1280px 50%"

[scratchpads.chatbox]
animation = "fromRight"
command = "chatbox"
class = "xyz.chatboxapp.app"
size = "33% 90%"
max_size = "1280px 90%"
lazy = true
excludes = ["volume"]

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "33% 66%"
excludes = ["chatbox"]
max_size = "1280px 66%"

# todo
# [scratchpads.firefox]
# animation = "fromBottom"
# command = ":"
# class = "top"
# class_match
# sizje = "70% 90%"
