[pyprland]
plugins = ["scratchpads"]

[scratchpads.dropterm]
animation = "fromTop"
# command = "kitty --class term-drop --config /home/kuba/.config/kitty/qterm.conf tmux new -A -s dropterm"
command = "kitty --class term-drop --config /home/kuba/.config/kitty/qterm.conf tmux attach -d -t dropterm"
class = "term-drop"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
smart_focus = false

[scratchpads.top]
animation = "fromBottom"
command = "kitty --class term_btm --config ~/.config/kitty/qterm.conf btm"
class = "term_btm"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
smart_focus = false

[scratchpads.nvtop]
animation = "fromBottom"
command = "kitty --class term_nvtop --config ~/.config/kitty/qterm.conf nvtop"
class = "term_nvtop"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
smart_focus = false

[scratchpads.slack]
animation = "fromBottom"
command = "/usr/bin/slack --ozone-platform=wayland --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer --silent"
match_by = "initialTitle"
initialTitle = "re:.*Slack$"
class = "Slack"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
smart_focus = false

[scratchpads.whatsapp]
animation = "fromBottom"
command = "whatsapp-for-linux"
class = "whatsapp-for-linux"
# command = "whatsie"
# class = "com.ktechpit.whatsie"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
smart_focus = false

[scratchpads.obsidian]
animation = "fromBottom"
command = "obsidian obsidian://open?vault=notes"
class = "obsidian"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
smart_focus = false

[scratchpads.ytmusic]
animation = "fromBottom"
command = "/usr/bin/youtube-music"
class = "YouTube Music"
lazy = true
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
smart_focus = false
skip_rules = ["aspect"]

# [scratchpads.onepass]
# animation = "fromBottom"
# command = "1password"
# class = "1Password"
# size = "33% 50%"
# max_size = "1280px 50%"

[scratchpads.chatbox]
animation = "fromRight"
command = "chatbox"
class = "xyz.chatboxapp.app"
size = "33% 90%"
max_size = "1280px 90%"
lazy = true
excludes = ["volume"]
smart_focus = false

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "33% 66%"
excludes = ["chatbox"]
smart_focus = false
max_size = "1280px 66%"

# TODO: pwa apps always cause problems
# [scratchpads.gmeet]
# animation = "fromRight"
# command = "/usr/bin/chromium --profile-directory=Default --app-id=kjgfgldnnfoeklkmfkjfagphfepbbdan"
# match_by = "initialClass"
# initialClass = "chrome-kjgfgldnnfoeklkmfkjfagphfepbbdan-Default"
# class = "chrome-kjgfgldnnfoeklkmfkjfagphfepbbdan-Default"
# process_tracking = false
# size = "50% 90%"
# max_size = "1920px 90%"
# smart_focus = false
# skip_windowrules = ["aspect", "workspace", "float"]

# TODO: breaks because of starting another process
[scratchpads.discord]
animation = "fromBottom"
command = "/usr/bin/chromium --profile-directory=Default --app=https://discord.com/app"
# match_by = "initialClass"
# initialClass = "chrome-discord.com__app-Default"
class = "chrome-discord.com__app-Default"
process_tracking = false
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
smart_focus = false
# skip_windowrules = ["aspect", "workspace"]

# todo
# [scratchpads.firefox]
# animation = "fromBottom"
# command = ":"
# class = "top"
# class_match
# size = "70% 90%"
