[pyprland]
plugins = ["scratchpads"]

[scratchpads.dropterm]
animation = "fromTop"
command = "kitty --class term-drop --config /home/kuba/.config/kitty/qterm.conf tmux attach -d -t dropterm"
class = "term-drop"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
# smart_focus = false

[scratchpads.top]
animation = "fromBottom"
command = "kitty --class term_btm --config ~/.config/kitty/qterm.conf btm"
class = "term_btm"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
# smart_focus = false

[scratchpads.nvtop]
animation = "fromBottom"
command = "kitty --class term_nvtop --config ~/.config/kitty/qterm.conf nvtop"
class = "term_nvtop"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
# smart_focus = false

[scratchpads.slack]
animation = "fromBottom"
#  --disable-gpu-compositing --ozone-platform=wayland --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer,WaylandWindowDecorations --disable-features=WaylandFractionalScaleV1 
command = "/usr/bin/slack --ozone-platform=wayland --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer,WaylandWindowDecorations"
match_by = "initialTitle"
initialTitle = "re:.*Slack$"
class = "Slack"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
# smart_focus = false

[scratchpads.whatsapp]
animation = "fromBottom"
command = "whatsapp-for-linux"
class = "whatsapp-for-linux"
# command = "whatsie"
# class = "com.ktechpit.whatsie"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
# smart_focus = false

[scratchpads.obsidian]
animation = "fromBottom"
command = "obsidian obsidian://open?vault=notes"
class = "obsidian"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
# smart_focus = false

[scratchpads.ytmusic]
animation = "fromBottom"
command = "/usr/bin/youtube-music"
class = "YouTube Music"
lazy = true
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
# smart_focus = false

[scratchpads.onepass]
animation = "fromBottom"
command = "1password"
class = "1Password"
size = "33% 50%"
max_size = "800px 600px"
# smart_focus = false

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "33% 66%"
# smart_focus = false
max_size = "1280px 66%"

# TODO: breaks because of starting another process
[scratchpads.discord]
animation = "fromBottom"
command = "/usr/bin/chromium --profile-directory=Default --app=https://discord.com/app"
# match_by = "initialClass"
# initialClass = "chrome-discord.com__app-Default"
class = "chrome-discord.com__app-Default"
process_tracking = false
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
# smart_focus = false
# skip_windowrules = ["aspect", "workspace"]

[scratchpads.dropfox]
animation = "fromBottom"
command = "/usr/bin/firefox-beta"
class = "Firefox Beta"
size = "90% 90%"
max_size = "1920px 90%"
excludes = "*"
