alias gwa='git worktree add'
alias gwls='git worktree list'
alias gwlck='git worktree lock'
alias gwmv='git worktree move'
alias gwp='git worktree prune'
alias gwdel='git worktree remove'
alias gwr='git worktree repair'
alias gwulck='git worktree unlock'
