#!/bin/bash

ICAT="kitty +kitten icat"
FONTH=15 # Size of one terminal row
FONTW=7 # Size of one terminal column

if [ "$1" = "clear" ]; then
  $ICAT --silent --clear
else
  $ICAT --silent --place $1x$2@$3x$4 "${PWD}/$5"
fi
