[settings]
default_target_type = "symbolic"

[all]
depends = ["shell", "nvim", "local", "wayland", "system"]

[shell.files]
"atuin.toml" = "~/.config/atuin/config.toml"
bat = "~/.config/bat"
"bottom.toml" = "~/.config/bottom/bottom.toml"
"eget.toml" = "~/.config/.eget.toml"
glab-cli = "~/.config/glab-cli"
k9s = "~/.config/k9s"
kitty = "~/.config/kitty"
lazygit = "~/.config/lazygit"
"luarocks-5.4.lua" = "~/.config/luarocks/config-5.4.lua"
ripgrep = "~/.config/ripgrep"
"starship.toml" = "~/.config/starship.toml"
systemd = "~/.config/systemd"
"tmux.conf" = "~/.config/tmux/tmux.conf"
tmux_theme = "~/.config/tmux/plugins/tmux/themes/catppuccin_gruvbox.tmuxtheme"
yazi = "~/.config/yazi"
zsh = "~/.config/zsh"
"zsh/.zshenv" = "~/.zshenv"
"zsh/scripts/tcreds.zsh" = "~/.local/bin/tcreds"

[nvim.files]
nvim = "~/.config/nvim"

[wayland.files]
"hypr" = "~/.config/hypr"
"waybar" = "~/.config/waybar"
"swaync" = "~/.config/swaync"
"swappy.conf" = "~/.config/swappy/config"
"rofi" = "~/.config/rofi"
"shikane.toml" = "~/.config/shikane/config.toml"
"pipewire.conf.d" = "~/.config/pipewire/pipewire.conf.d"
"wlogout" = "~/.config/wlogout"
"chrome-flags.conf" = "~/.config/chrome-flags.conf"
"tridactylrc" = "~/.config/tridactyl/tridactylrc"

[local.files]
"local/applications" = "~/.local/share/applications"
"local/bin" = "~/.local/bin"

[system.files]
"system/keyd.conf" = { target = "/etc/keyd/default.conf", type = "symbolic", owner = "root" }
"system/swayosd-libinput-backend.service" = { target = "/etc/systemd/system/swayosd-libinput-backend.service.d/override.conf", type = "symbolic", owner = "root" }
"system/NetworkManager-wait-online.service" = { target = "/etc/systemd/system/NetworkManager-wait-online.service.d/override.conf", type = "symbolic", owner = "root" }
"system/iwd.service" = { target = "/etc/systemd/system/iwd.service.d/override.conf", type = "symbolic", owner = "root" }
