[helpers]

[all]
depends = ["shell", "nvim", "local", "wayland"]

[shell.files]
"atuin.toml" = "~/.config/atuin/config.toml"
bat = "~/.config/bat/config"
"eget.toml" = { target = "~/.config/.eget.toml", type = "symbolic" }
glab-cli = "~/.config/glab-cli"
kitty = "~/.config/kitty"
ripgrep = "~/.config/ripgrep"
"sheldon.toml" = { target = "~/.config/sheldon/plugins.toml", type = "symbolic" }
systemd = { target = "~/.config/systemd", type = "symbolic" }
"tmux.conf" = "~/.config/tmux/tmux.conf"
tmux_theme = "~/.config/tmux/plugins/tmux/themes/catppuccin_gruvbox.tmuxtheme"
# "tmux.conf.local" = "~/.config/tmux/tmux.conf.local"
zsh = "~/.config/zsh"
"zsh/.zshenv" = "~/.zshenv"

[nvim.files]
nvim = "~/.config/nvim"

[wayland.files]
"hyprland.conf" = "~/.config/hypr/hyprland.conf"
"hyprpaper.conf" = "~/.config/hypr/hyprpaper.conf"
"gtk-4.0" = "~/.config/gtk-4.0"
"pyprland.toml" = "~/.config/hypr/pyprland.toml"
"mako.conf" = "~/.config/mako/config"
"waybar.conf" = "~/.config/waybar/config"
"waybar.css" = "~/.config/waybar/style.css"
"kanshi.conf" = "~/.config/kanshi/config"
"rofi_colors.rasi" = "~/.config/rofi/colors.rasi"
"rofi_config.rasi" = "~/.config/rofi/config.rasi"
"pipewire.conf.d" = "~/.config/pipewire/pipewire.conf.d"
"wlogout" = "~/.config/wlogout"

[local.files]
"local/applications" = "~/.local/share/applications"
