[helpers]

[all]
depends = ["shell", "nvim", "local", "wayland"]

[shell.files]
"atuin.toml" = "~/.config/atuin/config.toml"
bat = "~/.config/bat/config"
"eget.toml" = { target = "~/.config/.eget.toml", type = "symbolic" }
glab-cli = "~/.config/glab-cli"
kitty = "~/.config/kitty"
"luarocks-5.4.lua" = "~/.config/luarocks/config-5.4.lua"
ripgrep = "~/.config/ripgrep"
systemd = { target = "~/.config/systemd", type = "symbolic" }
"tmux.conf" = "~/.config/tmux/tmux.conf"
tmux_theme = "~/.config/tmux/plugins/tmux/themes/catppuccin_gruvbox.tmuxtheme"
zsh = "~/.config/zsh"
"zsh/.zshenv" = "~/.zshenv"
"zsh/scripts/tcreds.zsh" = "~/.local/bin/tcreds"

[nvim.files]
nvim = "~/.config/nvim"

[wayland.files]
"hypr" = "~/.config/hypr"
"waybar" = "~/.config/waybar"
"mako.conf" = "~/.config/mako/config"
"swaync" = "~/.config/swaync"
"rofi/config.rasi" = "~/.config/rofi/config.rasi"
"rofi/themes" = "~/.local/share/rofi/themes"
"kanshi.conf" = "~/.config/kanshi/config"
"pipewire.conf.d" = "~/.config/pipewire/pipewire.conf.d"
"wlogout" = "~/.config/wlogout"

[local.files]
"local/applications" = "~/.local/share/applications"
